apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: EKS-App-Test
  region: us-east-2

vpc:
  id: vpc-09f380e00d990bb2e
  cidr: "192.168.0.0/16"
  subnets:
    public:
      us-east-2a:
        id: subnet-0b3cbb92d1e26d781
      us-east-2b:
        id: subnet-07612b99343df770f
    private:
      us-east-2a:
        id: subnet-0e99c36f949f34136
      us-east-2b:
        id: subnet-029f21f17b0ef4a08

nodeGroups:
  - name: EKS-public-workers
    instanceType: t2.medium
    desiredCapacity: 2
  - name: EKS-private-workers
    instanceType: t2.medium
    desiredCapacity: 1
    privateNetworking: true