apiVersion: apps/v1
kind: Deployment
metadata:
  name: meme-gen
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: meme-gen
          image: 798832556350.dkr.ecr.us-east-2.amazonaws.com/ecr_app_test:latest
          ports:
            - containerPort: 5000